//! Implementation for lustre node `between` (see [Between](struct.Between.html)).
//!
//! Code generated by the [Kind 2 model checker][kind 2].
//!
//! [kind 2]: http://kind2-mc.github.io/kind2/ (The Kind 2 model checker)

// Deactiving lint warnings the transformation does not respect.
#![allow(
  non_upper_case_globals, non_snake_case, non_camel_case_types,
  unused_variables, unused_parens
)]

#![no_std]

use helpers::* ;

/// Entry point.
fn main() {
  // clap_and_run()
}


/// Stores the state for **top node** `between`.
///
/// # Inputs
///
/// | Lustre identifier | Type |
/// |:---:|:---|
/// | `low` | Real |
/// | `high` | Real |
/// | `x` | Real |
///
/// # Outputs
///
/// | Lustre identifier | Type |
/// |:---:|:---|
/// | `yes` | Bool |
///
/// # Sub systems
///
/// No subsystems for this system.
///
/// # Assertions
///
/// /// No assertions for this system.
///
/// # Assumptions
///
/// No assumptions for this system.
///
#[repr(C)]
  pub struct Between {
  /// Input: `between.usr.low`
  pub svar_low: Real,
  /// Input: `between.usr.high`
  pub svar_high: Real,
  /// Input: `between.usr.x`
  pub svar_x: Real,

  /// Output: `between.usr.yes`
  pub svar_yes: Bool,


}

impl Sys for Between {
  type Input = (
    Real, // svar_low (between.usr.low)
    Real, // svar_high (between.usr.high)
    Real, // svar_x (between.usr.x)
  ) ;
  type Output = (
    Bool, // svar_yes (between.usr.yes)
  ) ;
/*  fn arity() -> usize { 3 }
*//*  fn input_of(vec: Vec<String>) -> Result<Self::Input, String> {
        match vec.len() {
          n if n == Self::arity() => {
            (
              try!( parse::real(& vec[0]) ), 
              try!( parse::real(& vec[1]) ), 
              try!( parse::real(& vec[2]) ),
            ) 
          },
          n => Err(
            format!(
              "arity mismatch, expected {} but got {}: {:?}",
              Self::arity(), n, vec
            )
            
          ),
        }
      }

*/   fn init(input: Self::Input) -> Self {
    // |===| Retrieving inputs.
    let svar_low = input.0 ;
    let svar_high = input.1 ;
    let svar_x = input.2 ;
    
    // |===| Computing initial state.
    let svar_yes = ( if ((svar_x >= svar_low) & (svar_x <= svar_high)) { true } else {false } ) ;
    
    // |===| Checking assertions.
    
    
    
    
    // |===| Returning initial state.
    Between {
      // |===| Inputs.
      svar_low: svar_low,
      svar_high: svar_high,
      svar_x: svar_x,
      
      // |===| Outputs.
      svar_yes: svar_yes,
      
      // |===| Locals.
      
      
      // |===| Calls.
      
    } 
  }

  fn next(&mut self, input: Self::Input) {
    // |===| Retrieving inputs.
    let svar_low = input.0 ;
    let svar_high = input.1 ;
    let svar_x = input.2 ;
    
    // |===| Computing next state.
    let svar_yes = ( if ((svar_x >= svar_low) & (svar_x <= svar_high)) { true } else {false } ) ;
    
    // |===| Checking assertions.
    
    
    // |===| Checking assumptions.
    
    
    // |===| Updating next state.
    // |===| Inputs.
    self.svar_low = svar_low ;
    self.svar_high = svar_high ;
    self.svar_x = svar_x ;
    
    // |===| Outputs.
    self.svar_yes = svar_yes ;
    
    // |===| Locals.
    
    
    // |===| Calls.
    /**/ 
    
    // |===| Return new state.
    /*Ok( self )*/
  }

  fn output(& self) -> Self::Output {(
    self.svar_yes,
  )}
/*  fn output_str(& self) -> String {
      format!(
        "{}",
        self.svar_yes
      )
    }*/
}



/// Types and structures for systems.
pub mod helpers {
 /* use std::io::{ Stdin, stdin } ;
  use std::process::exit ;

  /// Prints usage.
  pub fn help() {
    println!("") ;
    println!("\
Options:
  -h, --help
    prints this message
  --between
    inputs:  Real (low)
             Real (high)
             Real (x)
    outputs: Bool (yes)
Usage:
  Inputs (outputs) are read (printed) as comma-separated values on a single
  line.
  The read-eval-print loop runs forever, write \"exit\" or \"quit\"
  to exit it cleanly.
Default system: \"between\".\
    ") ;
    println!("")
  }

  /// Prints usage, an error, and exits with status `2`.
  pub fn error<T: ::std::fmt::Display>(e: T) {
    help() ;
    println!("Error: {}", e) ;
    println!("") ;
    exit(2)
  }

  /// Handles CLA.
  pub fn clap_and_run() {
    use std::env::args ;
    let mut args = args() ;
    // Skipping first argument (name of binary).
    match args.next() {
      Some(_) => (),
      None => unreachable!(),
    } ;
    if let Some(arg) = args.next() {
      match & arg as & str {
        "-h" | "--help" => {
          help() ;
          exit(0)
        },
        "--between" => super::Between::run(),
        arg => error(
          format!("unexpected argument \"{}\".", arg)
        ),
      }
    } ;
    // If no argument given, run top system.
    super::Between::run()
  }*/

  /// Alias for `i64`.
  pub type Int = i64 ;
  /// Alias for `f64`.
  pub type Real = f64 ;
  /// Alias for `bool`.
  pub type Bool = bool ;

  /// Stores an `Stdin` and a buffer to read lines.
   /* pub struct InputReader {
    /// Standard input.
    stdin: Stdin,
    /// String buffer.
    buff: String,
  }
  impl InputReader {
    /// Creates an input reader.
    pub fn mk() -> Self {
      InputReader {
        stdin: stdin(),
        buff: String::with_capacity(100),
      }
    }
    /// Reads comma separated inputs from standard input.
    pub fn read_inputs(& mut self) -> Result<Vec<String>, String> {
      self.buff.clear() ;
      match self.stdin.read_line(& mut self.buff) {
        Ok(_) => (),
        Err(e) => return Err(
          format!("could not read line from stdin: {}", e)
        ),
      } ;
      let chars = self.buff.trim_left().chars() ;
      let mut buff = String::new() ;
      let mut vec = vec![] ;
      for c in chars {
        match c {
          ' ' | '\t' => (),
          ',' | '\n' => {
            vec.push(buff.clone()) ;
            buff.clear()
          },
          _ => buff.push(c),
        }
      } ;
      if vec.len() > 1 {
        match vec[0].trim() {
          "exit" | "quit" => exit(0),
          _ => ()
        }
      } ;
      Ok(vec)
    }
  } */

  /// Trait all systems must implement.
  pub trait Sys: Sized {
    /// Type of inputs.
    type Input ;
    /// Type of outputs.
    type Output ;
    /// Number of inputs expected.
    /*fn arity() -> usize ;
    /// Parses a vector of inputs.
    fn input_of(Vec<String>) -> Result<Self::Input, String> ;*/
    /// Initial state of the system.
    fn init(input: Self::Input) -> Self ;
    /// Computes the next step.
    fn next(&mut self, input: Self::Input) ;
    /// Reads inputs from standard input, computes initial state, prints output.
    /* fn read_init(reader: & mut InputReader) -> Result<Self, String> {
      match Self::input_of( try!(reader.read_inputs()) ) {
        Ok(inputs) => {
          let init = try!( Self::init(inputs) ) ;
          println!("{}", init.output_str()) ;
          Ok(init)
        },
        Err(s) => Err(s),
      }
    } */
    fn read_init(input: Self::Input) -> Self{
      Self::init(input)
    }

    /// Reads inputs from standard input, computes next step, prints output.
    /* fn read_next(self, reader: & mut InputReader) -> Result<Self, String> {
      match Self::input_of( try!(reader.read_inputs()) ) {
        Ok(inputs) => {
          let next = try!( self.next(inputs) ) ;
          println!("{}", next.output_str()) ;
          Ok(next)
        },
        Err(s) => Err(s),
      }
    } */
    fn read_next(&mut self, input: Self::Input){
      self.next(input);
    }

    /// Output of the system.
    fn output(& self) -> Self::Output ;
    // String representation of the output.
    // fn output_str(& self) -> String ;
    // Runs a never-ending, read-eval-print loop on the system.
    /* fn run() -> ! {
      let mut reader = InputReader::mk() ;
      let mut state = match Self::read_init(& mut reader) {
        Ok(init) => init,
        Err(e) => {
          println!("(Error: {})", e) ;
          exit(2)
        }
      } ;
      loop {
        match state.read_next(& mut reader) {
          Ok(next) => state = next,
          Err(e) => {
            println!("(Error: {})", e) ;
            exit(2)
          }
        }
      }
    } */
  }
}

// Parsing functions.
/* pub mod parse {
  use helpers::{ Int, Real, Bool } ;
  use std::fmt::Display ;
  use std::str::FromStr ;
  /// Generic parser to factor error handling out.
  fn generic<
    Out, Error: Display, F: Fn(& str) -> Result<Out, Error>
  >(s: & str, f: F, typ3: & 'static str) -> Result<Out, String> {
    match f(s) {
      Ok(res) => Ok(res),
      Err(e) => Err(
        format!("could not parse \"{}\" as {}: {}", s, typ3, e)
      ),
    }
  }
  /// Parses a [`Bool`](../type.Bool.html).
  pub fn bool(s: & str) -> Result<Bool, String> {
    generic(
      s,
      |s| match s {
        "true" | "on" => Ok(true),
        "false" | "off" => Ok(false),
        _ => Err(
          format!("legal values: true, on, false, off")
        ),
      },
      "a bool"
    )
  }
  /// Parses an [`Int`](../type.Int.html).
  pub fn int(s: & str) -> Result<Int, String> {
    generic(s, |s| Int::from_str(s), "an int")
  }
  /// Parses a [`Real`](../type.Real.html).
  pub fn real(s: & str) -> Result<Real, String> {
    generic(s, |s| Real::from_str(s), "a real")
  }
} */


