//! Implementation for lustre node `kmfuzzy` (see [Kmfuzzy](struct.Kmfuzzy.html)).
//!
//! Code generated by the [Kind 2 model checker][kind 2].
//!
//! [kind 2]: http://kind2-mc.github.io/kind2/ (The Kind 2 model checker)

// Deactiving lint warnings the transformation does not respect.
#![allow(
  non_upper_case_globals, non_snake_case, non_camel_case_types,
  unused_variables, unused_parens
)]

#![no_std]

use helpers::* ;

/// Entry point.
fn main() {
  // clap_and_run()
}


/// Stores the state for **top node** `kmfuzzy`.
///
/// # Inputs
///
/// | Lustre identifier | Type |
/// |:---:|:---|
/// | `i` | Real |
/// | `x` | Real |
///
/// # Outputs
///
/// | Lustre identifier | Type |
/// |:---:|:---|
/// | `y` | Real |
///
/// # Sub systems
///
/// No subsystems for this system.
///
/// # Assertions
///
/// /// No assertions for this system.
///
/// # Assumptions
///
/// No assumptions for this system.
///
#[repr(C)]
  pub struct Kmfuzzy {
  /// Input: `kmfuzzy.usr.i`
  pub svar_i: Real,
  /// Input: `kmfuzzy.usr.x`
  pub svar_x: Real,

  /// Output: `kmfuzzy.usr.y`
  pub svar_y: Real,

  /// Local, local: `kmfuzzy.impl.usr.dcenter7`
  pub svar_dcenter7: Real,
  /// Local, local: `kmfuzzy.impl.usr.dcenter6`
  pub svar_dcenter6: Real,
  /// Local, local: `kmfuzzy.impl.usr.dcenter5`
  pub svar_dcenter5: Real,
  /// Local, local: `kmfuzzy.impl.usr.dcenter4`
  pub svar_dcenter4: Real,
  /// Local, local: `kmfuzzy.impl.usr.dcenter3`
  pub svar_dcenter3: Real,
  /// Local, local: `kmfuzzy.impl.usr.dcenter2`
  pub svar_dcenter2: Real,
  /// Local, local: `kmfuzzy.impl.usr.dcenter1`
  pub svar_dcenter1: Real,
  /// Local, local: `kmfuzzy.impl.usr.pcenter7`
  pub svar_pcenter7: Real,
  /// Local, local: `kmfuzzy.impl.usr.pcenter6`
  pub svar_pcenter6: Real,
  /// Local, local: `kmfuzzy.impl.usr.pcenter5`
  pub svar_pcenter5: Real,
  /// Local, local: `kmfuzzy.impl.usr.pcenter4`
  pub svar_pcenter4: Real,
  /// Local, local: `kmfuzzy.impl.usr.pcenter3`
  pub svar_pcenter3: Real,
  /// Local, local: `kmfuzzy.impl.usr.pcenter2`
  pub svar_pcenter2: Real,
  /// Local, local: `kmfuzzy.impl.usr.pcenter1`
  pub svar_pcenter1: Real,

}

impl Sys for Kmfuzzy {
  type Input = (
    Real, // svar_i (kmfuzzy.usr.i)
    Real, // svar_x (kmfuzzy.usr.x)
  ) ;
  type Output = (
    Real, // svar_y (kmfuzzy.usr.y)
  ) ;
/*  fn arity() -> usize { 2 }
*//*  fn input_of(vec: Vec<String>) -> Result<Self::Input, String> {
        match vec.len() {
          n if n == Self::arity() => {
            (
              try!( parse::real(& vec[0]) ), 
              try!( parse::real(& vec[1]) ),
            ) 
          },
          n => Err(
            format!(
              "arity mismatch, expected {} but got {}: {:?}",
              Self::arity(), n, vec
            )
            
          ),
        }
      }

*/   fn init(input: Self::Input) -> Self {
    // |===| Retrieving inputs.
    let svar_i = input.0 ;
    let svar_x = input.1 ;
    
    // |===| Computing initial state.
    let svar_pcenter1 = - 1f64 ;
    let svar_pcenter2 = - 19f64 / 20f64 ;
    let svar_pcenter3 = - 9f64 / 10f64 ;
    let svar_pcenter4 = 0f64 ;
    let svar_pcenter5 = 9f64 / 10f64 ;
    let svar_pcenter6 = 19f64 / 20f64 ;
    let svar_pcenter7 = 1f64 ;
    let svar_dcenter1 = - 1f64 ;
    let svar_dcenter2 = - 3f64 / 10f64 ;
    let svar_dcenter3 = - 1f64 / 10f64 ;
    let svar_dcenter4 = 0f64 ;
    let svar_dcenter5 = 1f64 / 10f64 ;
    let svar_dcenter6 = 3f64 / 10f64 ;
    let svar_dcenter7 = 1f64 ;
    let svar_y = 0f64 ;
    
    // |===| Checking assertions.
    
    
    
    
    // |===| Returning initial state.
    Kmfuzzy {
      // |===| Inputs.
      svar_i: svar_i,
      svar_x: svar_x,
      
      // |===| Outputs.
      svar_y: svar_y,
      
      // |===| Locals.
      svar_dcenter7: svar_dcenter7,
      svar_dcenter6: svar_dcenter6,
      svar_dcenter5: svar_dcenter5,
      svar_dcenter4: svar_dcenter4,
      svar_dcenter3: svar_dcenter3,
      svar_dcenter2: svar_dcenter2,
      svar_dcenter1: svar_dcenter1,
      svar_pcenter7: svar_pcenter7,
      svar_pcenter6: svar_pcenter6,
      svar_pcenter5: svar_pcenter5,
      svar_pcenter4: svar_pcenter4,
      svar_pcenter3: svar_pcenter3,
      svar_pcenter2: svar_pcenter2,
      svar_pcenter1: svar_pcenter1,
      
      // |===| Calls.
      
    } 
  }

  fn next(&mut self, input: Self::Input) {
    // |===| Retrieving inputs.
    let svar_i = input.0 ;
    let svar_x = input.1 ;
    
    // |===| Computing next state.
    let svar_pcenter1 = - 1f64 ;
    let svar_pcenter2 = - 19f64 / 20f64 ;
    let svar_pcenter3 = - 9f64 / 10f64 ;
    let svar_pcenter4 = 0f64 ;
    let svar_pcenter5 = 9f64 / 10f64 ;
    let svar_pcenter6 = 19f64 / 20f64 ;
    let svar_pcenter7 = 1f64 ;
    let svar_dcenter1 = - 1f64 ;
    let svar_dcenter2 = - 3f64 / 10f64 ;
    let svar_dcenter3 = - 1f64 / 10f64 ;
    let svar_dcenter4 = 0f64 ;
    let svar_dcenter5 = 1f64 / 10f64 ;
    let svar_dcenter6 = 3f64 / 10f64 ;
    let svar_dcenter7 = 1f64 ;
    let svar_y = 0f64 ;
    
    // |===| Checking assertions.
    
    
    // |===| Checking assumptions.
    
    
    // |===| Updating next state.
    // |===| Inputs.
    self.svar_i = svar_i ;
    self.svar_x = svar_x ;
    
    // |===| Outputs.
    self.svar_y = svar_y ;
    
    // |===| Locals.
    self.svar_dcenter7 = svar_dcenter7 ;
    self.svar_dcenter6 = svar_dcenter6 ;
    self.svar_dcenter5 = svar_dcenter5 ;
    self.svar_dcenter4 = svar_dcenter4 ;
    self.svar_dcenter3 = svar_dcenter3 ;
    self.svar_dcenter2 = svar_dcenter2 ;
    self.svar_dcenter1 = svar_dcenter1 ;
    self.svar_pcenter7 = svar_pcenter7 ;
    self.svar_pcenter6 = svar_pcenter6 ;
    self.svar_pcenter5 = svar_pcenter5 ;
    self.svar_pcenter4 = svar_pcenter4 ;
    self.svar_pcenter3 = svar_pcenter3 ;
    self.svar_pcenter2 = svar_pcenter2 ;
    self.svar_pcenter1 = svar_pcenter1 ;
    
    // |===| Calls.
    /**/ 
    
    // |===| Return new state.
    /*Ok( self )*/
  }

  fn output(& self) -> Self::Output {(
    self.svar_y,
  )}
/*  fn output_str(& self) -> String {
      format!(
        "{}",
        self.svar_y
      )
    }*/
}



/// Types and structures for systems.
pub mod helpers {
 /* use std::io::{ Stdin, stdin } ;
  use std::process::exit ;

  /// Prints usage.
  pub fn help() {
    println!("") ;
    println!("\
Options:
  -h, --help
    prints this message
  --kmfuzzy
    inputs:  Real (i)
             Real (x)
    outputs: Real (y)
Usage:
  Inputs (outputs) are read (printed) as comma-separated values on a single
  line.
  The read-eval-print loop runs forever, write \"exit\" or \"quit\"
  to exit it cleanly.
Default system: \"kmfuzzy\".\
    ") ;
    println!("")
  }

  /// Prints usage, an error, and exits with status `2`.
  pub fn error<T: ::std::fmt::Display>(e: T) {
    help() ;
    println!("Error: {}", e) ;
    println!("") ;
    exit(2)
  }

  /// Handles CLA.
  pub fn clap_and_run() {
    use std::env::args ;
    let mut args = args() ;
    // Skipping first argument (name of binary).
    match args.next() {
      Some(_) => (),
      None => unreachable!(),
    } ;
    if let Some(arg) = args.next() {
      match & arg as & str {
        "-h" | "--help" => {
          help() ;
          exit(0)
        },
        "--kmfuzzy" => super::Kmfuzzy::run(),
        arg => error(
          format!("unexpected argument \"{}\".", arg)
        ),
      }
    } ;
    // If no argument given, run top system.
    super::Kmfuzzy::run()
  }*/

  /// Alias for `i64`.
  pub type Int = i64 ;
  /// Alias for `f64`.
  pub type Real = f64 ;
  /// Alias for `bool`.
  pub type Bool = bool ;

  /// Stores an `Stdin` and a buffer to read lines.
   /* pub struct InputReader {
    /// Standard input.
    stdin: Stdin,
    /// String buffer.
    buff: String,
  }
  impl InputReader {
    /// Creates an input reader.
    pub fn mk() -> Self {
      InputReader {
        stdin: stdin(),
        buff: String::with_capacity(100),
      }
    }
    /// Reads comma separated inputs from standard input.
    pub fn read_inputs(& mut self) -> Result<Vec<String>, String> {
      self.buff.clear() ;
      match self.stdin.read_line(& mut self.buff) {
        Ok(_) => (),
        Err(e) => return Err(
          format!("could not read line from stdin: {}", e)
        ),
      } ;
      let chars = self.buff.trim_left().chars() ;
      let mut buff = String::new() ;
      let mut vec = vec![] ;
      for c in chars {
        match c {
          ' ' | '\t' => (),
          ',' | '\n' => {
            vec.push(buff.clone()) ;
            buff.clear()
          },
          _ => buff.push(c),
        }
      } ;
      if vec.len() > 1 {
        match vec[0].trim() {
          "exit" | "quit" => exit(0),
          _ => ()
        }
      } ;
      Ok(vec)
    }
  } */

  /// Trait all systems must implement.
  pub trait Sys: Sized {
    /// Type of inputs.
    type Input ;
    /// Type of outputs.
    type Output ;
    /// Number of inputs expected.
    /*fn arity() -> usize ;
    /// Parses a vector of inputs.
    fn input_of(Vec<String>) -> Result<Self::Input, String> ;*/
    /// Initial state of the system.
    fn init(input: Self::Input) -> Self ;
    /// Computes the next step.
    fn next(&mut self, input: Self::Input) ;
    /// Reads inputs from standard input, computes initial state, prints output.
    /* fn read_init(reader: & mut InputReader) -> Result<Self, String> {
      match Self::input_of( try!(reader.read_inputs()) ) {
        Ok(inputs) => {
          let init = try!( Self::init(inputs) ) ;
          println!("{}", init.output_str()) ;
          Ok(init)
        },
        Err(s) => Err(s),
      }
    } */
    fn read_init(input: Self::Input) -> Self{
      Self::init(input)
    }

    /// Reads inputs from standard input, computes next step, prints output.
    /* fn read_next(self, reader: & mut InputReader) -> Result<Self, String> {
      match Self::input_of( try!(reader.read_inputs()) ) {
        Ok(inputs) => {
          let next = try!( self.next(inputs) ) ;
          println!("{}", next.output_str()) ;
          Ok(next)
        },
        Err(s) => Err(s),
      }
    } */
    fn read_next(&mut self, input: Self::Input){
      self.next(input);
    }

    /// Output of the system.
    fn output(& self) -> Self::Output ;
    // String representation of the output.
    // fn output_str(& self) -> String ;
    // Runs a never-ending, read-eval-print loop on the system.
    /* fn run() -> ! {
      let mut reader = InputReader::mk() ;
      let mut state = match Self::read_init(& mut reader) {
        Ok(init) => init,
        Err(e) => {
          println!("(Error: {})", e) ;
          exit(2)
        }
      } ;
      loop {
        match state.read_next(& mut reader) {
          Ok(next) => state = next,
          Err(e) => {
            println!("(Error: {})", e) ;
            exit(2)
          }
        }
      }
    } */
  }
}

// Parsing functions.
/* pub mod parse {
  use helpers::{ Int, Real, Bool } ;
  use std::fmt::Display ;
  use std::str::FromStr ;
  /// Generic parser to factor error handling out.
  fn generic<
    Out, Error: Display, F: Fn(& str) -> Result<Out, Error>
  >(s: & str, f: F, typ3: & 'static str) -> Result<Out, String> {
    match f(s) {
      Ok(res) => Ok(res),
      Err(e) => Err(
        format!("could not parse \"{}\" as {}: {}", s, typ3, e)
      ),
    }
  }
  /// Parses a [`Bool`](../type.Bool.html).
  pub fn bool(s: & str) -> Result<Bool, String> {
    generic(
      s,
      |s| match s {
        "true" | "on" => Ok(true),
        "false" | "off" => Ok(false),
        _ => Err(
          format!("legal values: true, on, false, off")
        ),
      },
      "a bool"
    )
  }
  /// Parses an [`Int`](../type.Int.html).
  pub fn int(s: & str) -> Result<Int, String> {
    generic(s, |s| Int::from_str(s), "an int")
  }
  /// Parses a [`Real`](../type.Real.html).
  pub fn real(s: & str) -> Result<Real, String> {
    generic(s, |s| Real::from_str(s), "a real")
  }
} */


