//! Implementation for lustre node `compute_pid` (see [Compute_pid](struct.Compute_pid.html)).
//!
//! Code generated by the [Kind 2 model checker][kind 2].
//!
//! [kind 2]: http://kind2-mc.github.io/kind2/ (The Kind 2 model checker)

// Deactiving lint warnings the transformation does not respect.
#![allow(
  non_upper_case_globals, non_snake_case, non_camel_case_types,
  unused_variables, unused_parens
)]

use helpers::* ;

/// Entry point.
fn main() {
  clap_and_run()
}


/// Stores the state for **top node** `compute_pid`.
///
/// # Inputs
///
/// | Lustre identifier | Type |
/// |:---:|:---|
/// | `Input` | Real |
/// | `Now` | Real |
/// | `Setpoint` | Real |
/// | `Kp` | Real |
/// | `Ki` | Real |
/// | `Kd` | Real |
/// | `SampleTime` | Real |
///
/// # Outputs
///
/// | Lustre identifier | Type |
/// |:---:|:---|
/// | `y` | Real |
///
/// # Sub systems
///
/// No subsystems for this system.
///
/// # Assertions
///
/// /// No assertions for this system.
///
/// # Assumptions
///
/// No assumptions for this system.
///
pub struct Compute_pid {
  /// Input: `compute_pid.usr.Input`
  pub svar_Input: Real,
  /// Input: `compute_pid.usr.Now`
  pub svar_Now: Real,
  /// Input: `compute_pid.usr.Setpoint`
  pub svar_Setpoint: Real,
  /// Input: `compute_pid.usr.Kp`
  pub svar_Kp: Real,
  /// Input: `compute_pid.usr.Ki`
  pub svar_Ki: Real,
  /// Input: `compute_pid.usr.Kd`
  pub svar_Kd: Real,
  /// Input: `compute_pid.usr.SampleTime`
  pub svar_SampleTime: Real,

  /// Output: `compute_pid.usr.y`
  pub svar_y: Real,


}

impl Sys for Compute_pid {
  type Input = (
    Real, // svar_Input (compute_pid.usr.Input)
    Real, // svar_Now (compute_pid.usr.Now)
    Real, // svar_Setpoint (compute_pid.usr.Setpoint)
    Real, // svar_Kp (compute_pid.usr.Kp)
    Real, // svar_Ki (compute_pid.usr.Ki)
    Real, // svar_Kd (compute_pid.usr.Kd)
    Real, // svar_SampleTime (compute_pid.usr.SampleTime)
  ) ;
  type Output = (
    Real, // svar_y (compute_pid.usr.y)
  ) ;
  fn arity() -> usize { 7 }
  fn input_of(vec: Vec<String>) -> Result<Self::Input, String> {
    match vec.len() {
      n if n == Self::arity() => {
        Ok( (
          try!( parse::real(& vec[0]) ), 
          try!( parse::real(& vec[1]) ), 
          try!( parse::real(& vec[2]) ), 
          try!( parse::real(& vec[3]) ), 
          try!( parse::real(& vec[4]) ), 
          try!( parse::real(& vec[5]) ), 
          try!( parse::real(& vec[6]) ),
        ) )
      },
      n => Err(
        format!(
          "arity mismatch, expected {} but got {}: {:?}",
          Self::arity(), n, vec
        )
        
      ),
    }
  }

  fn init(input: Self::Input) -> Result<Self, String> {
    // |===| Retrieving inputs.
    let svar_Input = input.0 ;
    let svar_Now = input.1 ;
    let svar_Setpoint = input.2 ;
    let svar_Kp = input.3 ;
    let svar_Ki = input.4 ;
    let svar_Kd = input.5 ;
    let svar_SampleTime = input.6 ;
    
    // |===| Computing initial state.
    let svar_y = ( if ((svar_Now - 0f64) >= svar_SampleTime) { (((svar_Kp * (svar_Setpoint - svar_Input)) + (((svar_Ki * (svar_Setpoint - svar_Input)) * svar_SampleTime) / 1000f64)) - (((svar_Kd * (svar_Input - 0f64)) * 1000f64) / svar_SampleTime)) } else {0f64 } ) ;
    
    // |===| Checking assertions.
    
    
    
    
    // |===| Returning initial state.
    Ok( Compute_pid {
      // |===| Inputs.
      svar_Input: svar_Input,
      svar_Now: svar_Now,
      svar_Setpoint: svar_Setpoint,
      svar_Kp: svar_Kp,
      svar_Ki: svar_Ki,
      svar_Kd: svar_Kd,
      svar_SampleTime: svar_SampleTime,
      
      // |===| Outputs.
      svar_y: svar_y,
      
      // |===| Locals.
      
      
      // |===| Calls.
      
    } )
  }

  fn next(mut self, input: Self::Input) -> Result<Self, String> {
    // |===| Retrieving inputs.
    let svar_Input = input.0 ;
    let svar_Now = input.1 ;
    let svar_Setpoint = input.2 ;
    let svar_Kp = input.3 ;
    let svar_Ki = input.4 ;
    let svar_Kd = input.5 ;
    let svar_SampleTime = input.6 ;
    
    // |===| Computing next state.
    let svar_y = ( if ((svar_Now - self.svar_Now) >= svar_SampleTime) { (((svar_Kp * (svar_Setpoint - svar_Input)) + (((svar_Ki * (svar_Setpoint - svar_Input)) * svar_SampleTime) / 1000f64)) - (((svar_Kd * (svar_Input - self.svar_Input)) * 1000f64) / svar_SampleTime)) } else {self.svar_y } ) ;
    
    // |===| Checking assertions.
    
    
    // |===| Checking assumptions.
    
    
    // |===| Updating next state.
    // |===| Inputs.
    self.svar_Input = svar_Input ;
    self.svar_Now = svar_Now ;
    self.svar_Setpoint = svar_Setpoint ;
    self.svar_Kp = svar_Kp ;
    self.svar_Ki = svar_Ki ;
    self.svar_Kd = svar_Kd ;
    self.svar_SampleTime = svar_SampleTime ;
    
    // |===| Outputs.
    self.svar_y = svar_y ;
    
    // |===| Locals.
    
    
    // |===| Calls.
    
    
    // |===| Return new state.
    Ok( self )
  }

  fn output(& self) -> Self::Output {(
    self.svar_y,
  )}
  fn output_str(& self) -> String {
    format!(
      "{}",
      self.svar_y
    )
  }
}



/// Types and structures for systems.
pub mod helpers {
  use std::io::{ Stdin, stdin } ;
  use std::process::exit ;

  /// Prints usage.
  pub fn help() {
    println!("") ;
    println!("\
Options:
  -h, --help
    prints this message
  --compute_pid
    inputs:  Real (Input)
             Real (Now)
             Real (Setpoint)
             Real (Kp)
             Real (Ki)
             Real (Kd)
             Real (SampleTime)
    outputs: Real (y)
Usage:
  Inputs (outputs) are read (printed) as comma-separated values on a single
  line.
  The read-eval-print loop runs forever, write \"exit\" or \"quit\"
  to exit it cleanly.
Default system: \"compute_pid\".\
    ") ;
    println!("")
  }

  /// Prints usage, an error, and exits with status `2`.
  pub fn error<T: ::std::fmt::Display>(e: T) {
    help() ;
    println!("Error: {}", e) ;
    println!("") ;
    exit(2)
  }

  /// Handles CLA.
  pub fn clap_and_run() {
    use std::env::args ;
    let mut args = args() ;
    // Skipping first argument (name of binary).
    match args.next() {
      Some(_) => (),
      None => unreachable!(),
    } ;
    if let Some(arg) = args.next() {
      match & arg as & str {
        "-h" | "--help" => {
          help() ;
          exit(0)
        },
        "--compute_pid" => super::Compute_pid::run(),
        arg => error(
          format!("unexpected argument \"{}\".", arg)
        ),
      }
    } ;
    // If no argument given, run top system.
    super::Compute_pid::run()
  }

  /// Alias for `i64`.
  pub type Int = i64 ;
  /// Alias for `f64`.
  pub type Real = f64 ;
  /// Alias for `bool`.
  pub type Bool = bool ;

  /// Stores an `Stdin` and a buffer to read lines.
  pub struct InputReader {
    /// Standard input.
    stdin: Stdin,
    /// String buffer.
    buff: String,
  }
  impl InputReader {
    /// Creates an input reader.
    pub fn mk() -> Self {
      InputReader {
        stdin: stdin(),
        buff: String::with_capacity(100),
      }
    }
    /// Reads comma separated inputs from standard input.
    pub fn read_inputs(& mut self) -> Result<Vec<String>, String> {
      self.buff.clear() ;
      match self.stdin.read_line(& mut self.buff) {
        Ok(_) => (),
        Err(e) => return Err(
          format!("could not read line from stdin: {}", e)
        ),
      } ;
      let chars = self.buff.trim_left().chars() ;
      let mut buff = String::new() ;
      let mut vec = vec![] ;
      for c in chars {
        match c {
          ' ' | '\t' => (),
          ',' | '\n' => {
            vec.push(buff.clone()) ;
            buff.clear()
          },
          _ => buff.push(c),
        }
      } ;
      if vec.len() > 1 {
        match vec[0].trim() {
          "exit" | "quit" => exit(0),
          _ => ()
        }
      } ;
      Ok(vec)
    }
  }

  /// Trait all systems must implement.
  pub trait Sys: Sized {
    /// Type of inputs.
    type Input ;
    /// Type of outputs.
    type Output ;
    /// Number of inputs expected.
    fn arity() -> usize ;
    /// Parses a vector of inputs.
    fn input_of(Vec<String>) -> Result<Self::Input, String> ;
    /// Initial state of the system.
    fn init(Self::Input) -> Result<Self, String> ;
    /// Computes the next step.
    fn next(self, Self::Input) -> Result<Self, String> ;
    /// Reads inputs from standard input, computes initial state, prints output.
    fn read_init(reader: & mut InputReader) -> Result<Self, String> {
      match Self::input_of( try!(reader.read_inputs()) ) {
        Ok(inputs) => {
          let init = try!( Self::init(inputs) ) ;
          println!("{}", init.output_str()) ;
          Ok(init)
        },
        Err(s) => Err(s),
      }
    }
    /// Reads inputs from standard input, computes next step, prints output.
    fn read_next(self, reader: & mut InputReader) -> Result<Self, String> {
      match Self::input_of( try!(reader.read_inputs()) ) {
        Ok(inputs) => {
          let next = try!( self.next(inputs) ) ;
          println!("{}", next.output_str()) ;
          Ok(next)
        },
        Err(s) => Err(s),
      }
    }
    /// Output of the system.
    fn output(& self) -> Self::Output ;
    /// String representation of the output.
    fn output_str(& self) -> String ;
    /// Runs a never-ending, read-eval-print loop on the system.
    fn run() -> ! {
      let mut reader = InputReader::mk() ;
      let mut state = match Self::read_init(& mut reader) {
        Ok(init) => init,
        Err(e) => {
          println!("(Error: {})", e) ;
          exit(2)
        }
      } ;
      loop {
        match state.read_next(& mut reader) {
          Ok(next) => state = next,
          Err(e) => {
            println!("(Error: {})", e) ;
            exit(2)
          }
        }
      }
    }
  }
}

/// Parsing functions.
pub mod parse {
  use helpers::{ Int, Real, Bool } ;
  use std::fmt::Display ;
  use std::str::FromStr ;
  /// Generic parser to factor error handling out.
  fn generic<
    Out, Error: Display, F: Fn(& str) -> Result<Out, Error>
  >(s: & str, f: F, typ3: & 'static str) -> Result<Out, String> {
    match f(s) {
      Ok(res) => Ok(res),
      Err(e) => Err(
        format!("could not parse \"{}\" as {}: {}", s, typ3, e)
      ),
    }
  }
  /// Parses a [`Bool`](../type.Bool.html).
  pub fn bool(s: & str) -> Result<Bool, String> {
    generic(
      s,
      |s| match s {
        "true" | "on" => Ok(true),
        "false" | "off" => Ok(false),
        _ => Err(
          format!("legal values: true, on, false, off")
        ),
      },
      "a bool"
    )
  }
  /// Parses an [`Int`](../type.Int.html).
  pub fn int(s: & str) -> Result<Int, String> {
    generic(s, |s| Int::from_str(s), "an int")
  }
  /// Parses a [`Real`](../type.Real.html).
  pub fn real(s: & str) -> Result<Real, String> {
    generic(s, |s| Real::from_str(s), "a real")
  }
}


